# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Bun Backend Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # Install Bun
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      # Add Bun to PATH
      - name: Setup Bun PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Install dependencies
      - run: bun install

      - run: bun run build

      # Run tests
      - run: bun test

      # Restart server
      - run: pm2 restart backendserver
